[tool.pytest.ini_options]
# https://docs.pytest.org/en/stable/reference/customize.html
# https://docs.pytest.org/en/stable/reference/reference.html#ini-options-ref
minversion = "8.0"
testpaths = [
    "tests",
    "integration",
]
# https://pytest-asyncio.readthedocs.io/en/latest/reference/configuration.html
asyncio_default_fixture_loop_scope = "session"
app_dotenv = ".env.test"
app_migration_file = "phone_books.db_schema:MIGRATION"
